version: '3.1'
services:
  stats-db:
    image: postgres:14-alpine
    container_name: db_stats_container
    ports:
      - "6541:5432"

    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=stats

  stats-server:
    build: ./stats/server
    image: stats_server_image
    container_name: stats_server_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - STRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=stats

  ewm-db:
    image: postgres:14-alpine
    container_name: db_ewm_container
    ports:
      - "6545:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm
    depends_on:
      - stats-server

  ewm-service:
    build: ./ewm
    image: ewm_image
    container_name: ewm_container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
