version: '3.1'
services:
  stats-db:
    image: postgres:14-alpine
    container_name: db_stats_container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=stats

  stats-server:
    build: ./ewm-stats/ewm-stats-server
    image: stats_server_image
    container_name: stats_server_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - STRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=stats

  ewm-db:
    image: postgres:14-alpine
    container_name: db_ewm_container
    ports:
      - "6545:5434"
    depends_on:
      - stats-server
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=main
      - POSTGRES_PASSWORD=main

  ewm-service:
    build: ./ewm-main
    image: ewm_image
    container_name: ewm_container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - MAIN_STRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5434/main
      - MAIN_POSTGRES_USER=main
      - MAIN_POSTGRES_PASSWORD=main